name: Multi-Environment Deployment
 
on:
  workflow_dispatch:
 
env:
  GLOBAL_ENV: "This is a global environment variable"
 
vars:
  APP_NAME: "MyWebApp"
 
jobs:
  log_context:
    runs-on: ubuntu-latest
    outputs:
repo_info: ${{ steps.repo_info.outputs.repo }}
    steps:
      - name: Log GitHub Context
        id: repo_info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "::set-output name=repo::${{ github.repository }}"
 
  deploy:
    needs: log_context
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    env:
      ENV_NAME: ${{ matrix.environment }}
    steps:
      - name: Print Deployment Info
        run: |
          echo "Deploying ${{ vars.APP_NAME }} to $ENV_NAME"
          echo "Triggered by: ${{ github.actor }}"
          echo "Global Env: $GLOBAL_ENV"
          echo "Repo Info from previous job: ${{ needs.log_context.outputs.repo_info }}"
 
      - name: Use Secrets
        run: |
          echo "Using secret token for $ENV_NAME"
          echo "${{ secrets.DEPLOYMENT_TOKEN }}"
 
 
